id: IBCC9989F
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T14:27:20.697377'
last_modified: '2022-06-19T14:27:20.697389'
parser: null
source_metadata:
  title: Hagiography of Sa skya paṇḍi ta Kun dga rgyal mtshan (1182-1251), no. III;
    Lamdre Lobshe, vol. ka, title no. 9, from the chronological biographies of the
    Lamdre lineage masters
  author: phags pa blo gros rgyal mtshan/
  description: 'Digital version 2.0 {Wylie}; WYLIE COPY of master xml (completed:
    2013-08-16); converted from external file, unrevised, no thematic TEI markup'
  file_info:
  - 'Language: Wylie'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:Sakya Research Centre (src)
  - Text input:rdzong sar khams bye'i lnga rig slob gling / sde dge rdzong sar/ (dzkj)
  - Editorial process:Mathias Fermer (mf), Kunga Dorje (kun)
  - TEI Encoding:Sakya Research Centre
  - TEI Markup:-
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/186
  bases:
    71b5:
      title: Hagiography of Sa skya paṇḍi ta Kun dga rgyal mtshan (1182-1251), no.
        III; Lamdre Lobshe, vol. ka, title no. 9, from the chronological biographies
        of the Lamdre lineage masters
      order: 1
      base_file: 71b5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
